version: "3"

services:
  api:
    restart: always
    container_name: "tobe_cv"
    image: "tobe_cv"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/tobe_cv
    env_file:
      - .env
